### ISSUE TITLE
"Welcome to travel planner" shouldn't be able to click.

### ISSUE THREAD

**Issue by KameriiJ** [narisasingngam/TravelPlanner#37]
I saw this title and highlighted it with cursor(just highlighted and think about its font ^^"), then it showed planners page. When I hover this title, my cursor is text cursor. So I think it shouldn't be able to click.

**Comment by jampttws** [comment]
It's about our design that user can click that picture and go to view planner page. "Welcome to travel planner" just a message for greeting new user.
