### ISSUE TITLE
Cannot save planner even when I have already sign in.

### ISSUE THREAD

**Issue by KorawitRupanya** [narisasingngam/TravelPlanner#39]
The save button doesn't work.

**Comment by narisasingngam** [comment]
Are you already confirm the planner after click "save" ?  
![image](https://user-images.githubusercontent.com/32285927/49383760-1368a380-f74c-11e8-9b33-e28108d35c73.png)

**Comment by KorawitRupanya** [comment]
<img width="1141" alt="screen shot 2561-12-03 at 22 42 38" src="https://user-images.githubusercontent.com/32285708/49384105-e10b7600-f74c-11e8-9f0a-ed4590fd52c7.png">
I got this page.

**Comment by narisasingngam** [comment]
You need to add two destination before saving.

**Comment by KorawitRupanya** [comment]
OK!!!
